/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.env.register.ui;

import com.env.register.model.Account;
import lombok.Getter;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
@Getter
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    public List<Account> getAccounts() {
        String[] lines = this.txta_input.getText().split("\n");
        if(lines.length == 0){
            JOptionPane.showMessageDialog(this, "Input is empty");
            return new ArrayList<>();
        }
        List<Account> accounts = new ArrayList<>();
        String password = this.txt_password.getText();
        if (password.trim().length() < 6) {
            JOptionPane.showMessageDialog(this, "Invalid password");
            return new ArrayList<>();
        }
        for(String line : lines) {
            String[] elements = line.split("\t");
            if (elements.length == 0) {
                elements = line.split(" ");
            }
            // Ten Dang Nhap [Khoang trang] SDT
            if(elements.length != 2) {
                JOptionPane.showMessageDialog(this, String.format("Invalid account line %s", line));
                return new ArrayList<>();
            }
            accounts.add(Account.builder()
                    .userName(elements[0])
                    .password(password)
                    .phoneNumber(elements[1])
                    .build());
        }
        return accounts;
    }

    public int getThreads() {
        int threads = 0;
        try {
            threads = Integer.parseInt(this.spinner_threads.getValue().toString());
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Threads");
        }
        return threads;
    }

    public synchronized void addOutput(Account account) {
        this.txta_output.append(String.format("%s\n", account.toOutput()));
    }

    public synchronized void addOutputAccError(Account account) {
        this.txta_account_error.append(String.format("%s\n", account.toOutput()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_main = new javax.swing.JPanel();
        label_input = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_input = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txta_output = new javax.swing.JTextArea();
        label_input1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        spinner_threads = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        txt_2captcha = new javax.swing.JTextField();
        btn_start = new javax.swing.JButton();
        btn_stop = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txta_logs = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txta_account_error = new javax.swing.JTextArea();
        label_input2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EVN Register v1.0");

        panel_main.setBackground(new java.awt.Color(51, 153, 255));

        label_input.setBackground(new java.awt.Color(255, 255, 255));
        label_input.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_input.setForeground(new java.awt.Color(255, 255, 255));
        label_input.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_input.setText("Input");

        txta_input.setColumns(20);
        txta_input.setRows(5);
        jScrollPane1.setViewportView(txta_input);

        txta_output.setColumns(20);
        txta_output.setRows(5);
        jScrollPane2.setViewportView(txta_output);

        label_input1.setBackground(new java.awt.Color(255, 255, 255));
        label_input1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_input1.setForeground(new java.awt.Color(255, 255, 255));
        label_input1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_input1.setText("Output");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");

        txt_password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_password.setText("123456");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Threads");

        spinner_threads.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        spinner_threads.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("2Captcha API Key");

        txt_2captcha.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        txt_2captcha.setText("755e69ea2d05c0cae0667ab3d8f64bbc");

        btn_start.setBackground(new java.awt.Color(0, 102, 204));
        btn_start.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn_start.setForeground(new java.awt.Color(255, 255, 255));
        btn_start.setText("Start");
        btn_start.setContentAreaFilled(false);
        btn_start.setOpaque(true);

        btn_stop.setBackground(new java.awt.Color(204, 0, 51));
        btn_stop.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btn_stop.setForeground(new java.awt.Color(255, 255, 255));
        btn_stop.setText("Stop");
        btn_stop.setContentAreaFilled(false);
        btn_stop.setOpaque(true);

        txta_logs.setBackground(new java.awt.Color(0, 0, 0));
        txta_logs.setColumns(20);
        txta_logs.setForeground(new java.awt.Color(255, 255, 255));
        txta_logs.setRows(5);
        txta_logs.setText("==== Welcome to EVN Register Tool By Van Lam ====");
        jScrollPane3.setViewportView(txta_logs);

        txta_account_error.setColumns(20);
        txta_account_error.setRows(5);
        jScrollPane4.setViewportView(txta_account_error);

        label_input2.setBackground(new java.awt.Color(255, 255, 255));
        label_input2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        label_input2.setForeground(new java.awt.Color(255, 255, 255));
        label_input2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_input2.setText("Acc Dang Ky Loi");

        javax.swing.GroupLayout panel_mainLayout = new javax.swing.GroupLayout(panel_main);
        panel_main.setLayout(panel_mainLayout);
        panel_mainLayout.setHorizontalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(label_input, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_mainLayout.createSequentialGroup()
                                .addComponent(btn_start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(btn_stop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txt_2captcha)
                            .addGroup(panel_mainLayout.createSequentialGroup()
                                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_mainLayout.createSequentialGroup()
                                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(18, 18, 18)
                                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                            .addGroup(panel_mainLayout.createSequentialGroup()
                                                .addComponent(spinner_threads, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                                .addGap(102, 102, 102))))
                                    .addComponent(jLabel3))
                                .addGap(6, 6, 6)))))
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_input1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                            .addComponent(label_input2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        panel_mainLayout.setVerticalGroup(
            panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_mainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addComponent(label_input)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_mainLayout.createSequentialGroup()
                                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spinner_threads, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_2captcha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_start, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addComponent(label_input1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                    .addGroup(panel_mainLayout.createSequentialGroup()
                        .addComponent(label_input2)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(panel_main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel label_input;
    private javax.swing.JLabel label_input1;
    private javax.swing.JLabel label_input2;
    private javax.swing.JPanel panel_main;
    private javax.swing.JSpinner spinner_threads;
    private javax.swing.JTextField txt_2captcha;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextArea txta_account_error;
    private javax.swing.JTextArea txta_input;
    private javax.swing.JTextArea txta_logs;
    private javax.swing.JTextArea txta_output;
    // End of variables declaration//GEN-END:variables
}
